config/routes.rb
OzjapaneseComAu::Application.routes.draw do
  
  resources :ozmains, :only => ["index"] do
    collection do
      get :about
      post :uzatt
      post :recent_top_feed
      post :recent_comment_feed
    end
  end
  
  resources :sessions, :only => [] do
    collection do
      post :signin
    end
  end
  
  devise_for :flyers, :controllers => { :omniauth_callbacks => "flyers/omniauth_callbacks" }
  
  resources :ozs, :only => ['index'] do
    collection do
      get :older
      get :newer
      get :write
      get :cancel
      post :viewed
      get :link_view
      post :carousel_viewed
      get :feed_view
      post :select_heading
      post :upload_image
    end
  end
  
  
  resources :terms, :only => ["index","create"]
  resources :images, :only => ["create"]
  resources :oz_employments, :only => ["create"]
  resources :oz_employers, :only => ["create"]
  resources :oz_sell_goods, :only => ["create"]
  resources :oz_buy_goods, :only => ["create"]
  resources :oz_estate_share_rents, :only => ["create"]
  resources :oz_info_events, :only => ["create"]
  resources :oz_people_pros, :only => ["create"]
  resources :oz_info_living_smarts, :only => ["create"]
  resources :oz_info_living_qnas, :only => ["create"]
  
  resources :contacts, :only => ["index","new","create"]
  resources :comments, :only => ['index'] do
  collection do
      post :post_comment
      post :view_all
    end
  end
  
  match 'counters/batch', :via => :get

  root :to => 'ozmains#index'

end

app/controllers/oz_controller.rb
class OzController < ApplicationController

  def _model(p)
    OzjapaneseStyle.heading_model(p)
  end
  
end

app/controllers/ozs_controller.rb
class OzsController < OzController
  
  before_filter :_before_, :except => [:carousel_viewed]
  before_filter :authenticate_flyer!, :only => [:write, :upload_image]

  def _before_
    raise "Bad Request" if params[:v].nil?
    logger.debug("v: #{params[:v]} d: #{params[:d]}")
    @board = Ozlink.param_v(params[:v])
    redirect_to root_path and return if !@board.present?
    @@board_id = params[:d].present? ? Ozlink.param_to_i(params[:d]) : nil
    logger.debug("@board: #{@board} board_id: #{@@board_id}")
    @heading = @board.to_sym
  end
  
  def index
    newer
  end
  
  def older
    collect_posts :older
    breadcrumb :older, @heading
    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  def newer
    collect_posts :newer
    breadcrumb :newer, @heading
    respond_to do |format|
      format.html # index.html.erb
    end 
  end
  
  def write
    @post = _model(@heading).new
    session["flyer_return_to"] = request.original_url
    @post.write_at = Common.current_time.to_i
    @post.build_content
    @post.valid_until = PostDef.post_expiry
    @image = Image.new(:write_at => @post.write_at)
    breadcrumb :write, @heading
    logger.debug("write image #{@image}")
    @post
  end
  
  def cancel
    redirect_to Ozlink.heading_link(@heading,"")
  end
  
  # non-Ajax Request
  def link_view
    viewed
    # Populate posts before and after
    @older_posts = _model(@heading).search_before(3, @post.id)
    @newer_posts = _model(@heading).search_after(3, @post.id)
    breadcrumb :link_view, @post
    respond_to do |format|
      format.html # link_view.html.erb
    end 
  end
  
  # Ajax
  def viewed
    @post = _model(@heading).find(@@board_id)
    @post.viewed
    @comment = Comment.new
    @comment.commented_id = @post.id
    @comment.commented_type = @heading
    @comments = Comment.comment_for(@post.id).limit(PostDef::NUMBER_OF_COMMENT)
    @post
  end
  
  def carousel_viewed
    @heading = params[:p].split("-")[0].to_sym
    @@board_id = params[:p].split("-")[1]
    logger.debug("carousel_viewed #{@heading} with #{@@board_id}")
    if !@heading.present? || !@@board_id.present?
      raise "Bad Request for carousel_viewed"
    end
    viewed
  end
  
  def feed_view
    feed_type = params[:f].present? ? Ozlink.param_to_s(params[:f]) : nil
    logger.debug("feed_view feed_type: #{feed_type}")
    raise "Bad Feed View Request" if !feed_type.present?
    model_name = OzjapaneseStyle.heading_model_name(@heading)
    case feed_type
     when "recent_week"
       feed = TopFeedList.recent_feed(model_name, 2)
     when "today"
       feed = TopFeedList.feed_for_date(model_name, 0)
     when "yesterday"
       feed = TopFeedList.feed_for_date(model_name, 1)
     else
       raise "Bad feed type #{feed_type}"
    end
    if feed.present?
      @comment = Comment.new
      @posts = feed.collect{ |f| f.feeded_to }
      logger.debug("feed_view: #{@posts.size}")
      @comment.commented_id = @posts.first.id
      @comment.commented_type = @heading
      @comments = Comment.comment_for(@posts.first.id).limit(PostDef::NUMBER_OF_COMMENT)
    end
    
  end
  
  def select_heading
    case @heading
    when :ozj_all
      @feed = Hash.new
      @feed_cnt = Hash.new
      OzjapaneseStyle.headings.each do |heading|
        model_name = OzjapaneseStyle.heading_model_name(heading)
        date_feed = Array.new
        0.upto(1) { |d|
          date_feed[d] = TopFeedList.feed_for_date(model_name, d).count
          logger.debug("date_feed[#{d}]: #{date_feed[d]}")
        }
        @feed[heading.to_sym] = date_feed
        @feed_cnt[heading.to_sym] = TopFeedList.recent_feed(model_name, 2).count
        logger.debug("@feed[#{heading}]: #{@feed[heading.to_sym]}")
        logger.debug("@feed_cnt[#{heading}]: #{@feed_cnt[heading.to_sym]}")
      end
    when :ozj_h1
      collect_posts :newer
    when :ozj_h2
      collect_posts :newer
    when :ozj_h3
      collect_posts :newer
    when :ozj_h4
      collect_posts :newer
    when :ozj_h5
      collect_posts :newer
    when :ozj_h6
      collect_posts :newer
    when :ozj_h8
      collect_posts :newer
    when :ozj_h9
      collect_posts :newer
    when :ozj_h7
    when :ozj_h11
    else
      raise "Bad Request #{@heading}"
    end
  end
  
  private
  
  def collect_posts(newer_or_older)
    model = _model(@heading)
    raise "Bad Board Request" if model.nil?
    if newer_or_older.eql? :newer
      @posts = model.search_newer_than(PostDef::POST_DISPLAY_NUMBER, PostDef::POST_OLDER)
    elsif newer_or_older.eql? :older
      @posts = model.search_older_than(PostDef::POST_DISPLAY_NUMBER, PostDef::POST_OLDER)
    end
    if @posts.present?
      @comment = Comment.new
      @comment.commented_id = @posts.first.id
      @comment.commented_type = @heading
      @comments = Comment.comment_for(@posts.first.id).limit(PostDef::NUMBER_OF_COMMENT)
    end
    logger.debug("@posts: #{@posts.size}")
    @posts
  end

end

app/views/ozs/_comment_form.html.erb
<div class="comment_form">
	<%= form_for(@comment) do |f| %>
	<%= f.text_area :body, :style => "width:300px;height:50px", :id => "comment_area" %>
	<div class="left">
		<p><%= link_to(t("post.comment_new"), "#", :class => "btn btn-info btn-small", :id => "submit_comment")%></p>
		<p class="text-success">
			<label class="checkbox">
			<input type="checkbox" value="">
			<%=t("post.comment_facebook_new")%>
		</label>
		</p>	
	</div>
	<% end %>
	<%= _script(%Q|$('\#submit_comment').click(function(){
		if($('\#comment_area').val() == ""){
			return false;
		}
		$('\#post_comment_area').html('#{image_tag("ajax-loader.gif")}');| +
		Ajax.post(post_comment_comments_path, %Q|authenticity_token: $("input[name='authenticity_token']").attr("value"), v: '#{Ozlink.base(@comment.commented_type)}', d: '#{Ozlink.param_enc(@comment.commented_id)}', m: $('\#comment_area').attr("value")|) +
		%Q|return false;
	})
	|)%>
</div>

app/views/ozs/_index.html.erb
<div class="container-fluid">

<div class="row-fluid" style="min-height: 600px">
	<div class="span6">
	<%= show_notice%>
	<% token = Common.uniqe_token %>
	<%= build_board_list(token) %>
	<%= _script(%Q|
	function view_post_#{token}() {
		$('\#side_post_area').html('#{image_tag("ajax-loader.gif")}');
		$('\#side_comment_thread').html('');
	}
	function comment_post_#{token}() {
		$('\#post_comment_area').html('#{image_tag("ajax-loader.gif")}');
	}
	|)%>
	</div>
	
	<div class="span6">
		<div id="side_post_bar">
		<div class="btn-toolbar">
			<div class="btn-group">
				<%= link_to_with_icon("#{t("post.newer")}",Ozlink.heading_link(@heading,"newer"),"btn btn-link","","icon-plus","")%>
			</div>
			<div class="btn-group">
				<%= link_to_with_icon("#{t("post.older")}",Ozlink.heading_link(@heading,"older"),"btn btn-link","","icon-tag","")%>
			</div>
			<div class="btn-group">
				<%= link_to_with_icon("#{t("post.back")}",root_path,"btn btn-link","","icon-home","")%>
			</div>
			<div class="btn-group">
				<%= post_write_new(@heading, :signin_with_following)%>
			</div>
		</div>
		<div id="side_post_area">
			<% if @posts.present? %>
				<div class="span8" id="side_post_thread_<%=@posts.first.id%>">
				<%= show_a_post(@posts.first, @heading)%>
				</div>
				<div class="span4" id="side_comment_thread_<%=@posts.first.id%>">
				<%= show_comment_thread(@posts.first, @heading)%>
				</div>
			<% end %>
		</div>
	</div>
	<style>
		#side_post_bar {
			position: fixed;
			top: 50px;
		}
	</style>
	</div>
</div>
</div>

app/views/ozs/_viewed.html.erb
<div class="span8" id="side_post_thread_<%= @post.id%>">
	<%= show_a_post(@post, @heading)%>
</div>
<div class="span4" id="side_comment_thread_<%= @post.id%>">
	<%= show_comment_thread(@post, @heading)%>
</div>

app/views/ozs/carousel_viewed.js.erb
$("#carousel_view_<%=@heading%>_<%=@post.id%>").html("<%= "#{t("post.viewed")} #{@post.views}" %>");
$('#side_comment_area').html("<%= escape_javascript(render 'ozmains/carousel_comment')%>")

app/views/ozs/feed_view.js.erb
$('#open_view').show();
$('#open_view').html("<%= escape_javascript(render 'ozmains/open_view') %>");

app/views/ozs/index.html.erb
<div class="container-fluid">
<%= show_notice%>
<div class="row-fluid">
	<div class="span6">
	<% token = Common.uniqe_token %>
	<%= build_board_list(token) %>
	<%= _script(%Q|
	function view_post_#{token}() {
		$('\#side_post_area').html('#{image_tag("ajax-loader.gif")}');
		$('\#side_comment_thread').html('');
	}
	function comment_post_#{token}() {
		$('\#post_comment_area').html('#{image_tag("ajax-loader.gif")}');
	}
	|)%>
	</div>
	<div class="span6">
		<div id="side_post_bar">
		<div class="btn-toolbar">
			<div class="btn-group">
				<%= link_to_with_icon("#{t("post.back")}",root_path,"btn","","icon-home","")%>
			</div>
			<div class="btn-group">
				<%= post_write_new(@heading, :signin_with_following)%>
			</div>
		</div>
		<div class="row-fluid">
			<% if @board_lists.present? %>
				<div class="span8" id="side_post_area">
				<%= show_a_post(@board_lists.first, @heading)%>
				</div>
				<div class="span4" id="side_comment_thread">
				<%= show_comment_thread(@board_lists.first, @heading)%>
				</div>
			<% end %>
		</div>
	</div>
	<style>
		#side_post_bar {
			position: relative;
			top: 50px;
		}
		
	</style>
	</div>
</div>

app/views/ozs/link_view.html.erb
<div class="container-fluid">
	<div class="row-fluid">
	<div class="row-fluid" style="margin-top:10px">
			<ul class="thumbnails">
			<% i=1 %>
			<% @older_posts.reverse_each do |post| %>
			<li class="link_view_top opacity_<%=i*20%>">
				<%= show_a_post_box(post) %>
				<% i += 1 %>
			</li>
			<% end %>				
			<li class="link_view_top opacity_100">
				<%= show_a_post_box(@post) %>
			</li>
			<% i=1 %>
			<% @newer_posts.reverse_each do |post| %>
			<li class="link_view_top opacity_<%=100-(i*20)%>">
				<%= show_a_post_box(post) %>
				<% i += 1 %>
			</li>
			<% end %>	
		</ul>
	</div>
	<div class="row-fluid">

		<div class="btn-toolbar">
			<div class="btn-group">
				<%= link_to_with_icon("#{t("post.newer")}",Ozlink.heading_link(@heading,"newer"),"btn btn-link","","icon-plus","")%>
			</div>
			<div class="btn-group">
				<%= link_to_with_icon("#{t("post.older")}",Ozlink.heading_link(@heading,"older"),"btn btn-link","","icon-tag","")%>
			</div>
			<div class="btn-group">
				<%= link_to_with_icon("#{t("post.back")}",root_path,"btn btn-link","","icon-home","")%>
			</div>
			<div class="btn-group">
				<%= post_write_new(@heading, :signin_with_following)%>
			</div>
		</div>
		<div class="row-fluid">
				<div class="span8" id="side_post_area">
				<%= show_a_post(@post, @heading)%>
				</div>
				<div class="span4" id="side_comment_thread_<%=@post.id%>">
				<%= show_comment_thread(@post, @heading)%>
				</div>
		</div>
	</div>
</div>

app/views/ozs/newer.html.erb
<%= render :partial => "ozs/index" %>

app/views/ozs/older.html.erb
<%= render :partial => "ozs/index" %>

app/views/ozs/select_heading.js.erb
<% if @heading.eql? :ozj_all %>
$('#heading_group_all').html("<%= escape_javascript(render 'ozmains/all_heading')%>");
<% elsif @heading.eql? :ozj_h7 %>
$('#heading_group_all').html("<%= escape_javascript(render 'pros/view_heading')%>");
<% elsif @heading.eql? :ozj_h11 %>
$('#heading_group_all').html("<%= escape_javascript(render 'meeting_points/view_heading')%>");
<% else %>
$('\#open_view').hide("slow");$('\#open_view').html("");
$('#heading_group_all').html("<%= escape_javascript(render 'ozmains/view_heading')%>");
<% end %>

app/views/ozs/viewed.js.erb
$('#side_post_area').focus();
$('#side_post_area').html("<%= escape_javascript(render 'ozs/viewed') %>");

app/views/ozs/write.html.erb
<% browser = Browser.browser_detection(request) %>

<div class="row-fluid" id="write_new">
	<div class="span9 offset2">
		<div class="post-alert">
			<div class="alert alert-block alert-info fade in">
				<button type="button" class="close" data-dismiss="alert">
					×
				</button>
				<h4 class="alert-heading"><%= t("post.alert.header")%></h4>
				<hr>
				<p>
					<i class="icon-check"></i>&nbsp;<%= t("post.alert.body1")%>
				</p>
				<p>
					<i class="icon-check"></i>&nbsp;<%= t("post.alert.body2")%>
				</p>
				<p>
					<i class="icon-check"></i>&nbsp;<%= t("post.alert.body3")%>
				</p>
				<p>
					<i class="icon-check"></i>&nbsp;<%= t("post.alert.body4")%>
				</p>
				<p>
					<a class="btn" href="<%=about_ozmains_path(:t => "service")%>"><%= t("terms_of_service_agreement")%></a>&nbsp;<a class="btn" href="<%=about_ozmains_path(:t => "personal")%>"><%= t("terms_of_personal_agreement")%></a>
				</p>
			</div>
		</div>
		<p class="text-success">
			<strong> <%= t("post.category") %> : <%= t(@post.class) %></strong>
		</p>
		<%= form_for(@post, :remote => true) do |f| %>
		<div class="pull-right">
			<span class="label label-info"><%= t("post.author") %></span>&nbsp;<i class="icon-user"></i><%= current_flyer.flyer_name %>
		</div>
		<%= f.hidden_field :write_at, :id => "write_at" %>
		<%= f.label :subject, t("post.subject") %>
		<%= f.text_field :subject, :class => "input-xxlarge", :placeholder => t("post.write_something") %>
		<%= label_tag t("post.valid_until") %>
		<span class="label label-info"><%= Common.date_format(@post.valid_until) %></span>
		<span class="help-block"><%= t("post.why_valid_until", :days => PostDef::POST_EXPIRY) %></span>
		<%= f.fields_for @post.content do |content_form| %>
		<%= content_form.label :body, t("post.content") %>
		<%= content_form.text_area :body, :style => "width:500px;height:200px" %>		
		<% end %>
		<br>
		<% if current_flyer && current_flyer.facebook_flyer? %>
		<p class="text-info">
			<label class="checkbox">
			<input type="checkbox" value="" id="post_to_facebook">
			<%=t("post.post_facebook_new")%>
		</label>
		<% end %>
		</p>
		<div id="post_errors"></div>
		<%= f.submit t("post.create"), :class => "btn btn-primary", :id => "post_submit" %>
		<%= link_to(t("post.cancel"), Ozlink.heading_link(@heading,"cancel"), :class => "btn") %>
		<div id="post_status"></div>
		<div id="post_facebook_script"></div>
		<div id="post_facebook_status"></div>
		<%= _script(%Q|
			$('\#post_submit').click(function(){
				$(this).attr("value",'#{t("post.creating")}');
				$(this).attr("css",'diabled');
				$(this).attr("disabled", true);
				$('\#post_status').html('#{image_tag("ajax-loader.gif")}');
				if($('\#post_to_facebook').attr("checked") == "checked") {
					$('\#post_facebook_status').html('#{image_tag("ajax-loader.gif")}');
				}
			})
		
		|)%>
		<%= _script_document_ready(%Q|$('#post_submit').attr("disabled", false);|)%>
		<% end %>
		<!-- image upload -->
		<%= render :partial => "ozs/upload/image"%>
	</div>
</div>