config/routes.rb
OzjapaneseComAu::Application.routes.draw do
  
  resources :ozmains, :only => ["index"] do
    collection do
      get :about
      post :uzatt
      post :recent_top_feed
      post :recent_comment_feed
    end
  end
  
  resources :sessions, :only => [] do
    collection do
      post :signin
    end
  end
  
  devise_for :flyers, :controllers => { :omniauth_callbacks => "flyers/omniauth_callbacks" }
  
  resources :ozs, :only => ['index'] do
    collection do
      get :older
      get :newer
      get :write
      get :cancel
      post :viewed
      get :link_view
      post :carousel_viewed
      get :feed_view
      post :select_heading
      post :upload_image
    end
  end
  
  
  resources :terms, :only => ["index","create"]
  resources :images, :only => ["create"]
  resources :oz_employments, :only => ["create"]
  resources :oz_employers, :only => ["create"]
  resources :oz_sell_goods, :only => ["create"]
  resources :oz_buy_goods, :only => ["create"]
  resources :oz_estate_share_rents, :only => ["create"]
  resources :oz_info_events, :only => ["create"]
  resources :oz_people_pros, :only => ["create"]
  resources :oz_info_living_smarts, :only => ["create"]
  resources :oz_info_living_qnas, :only => ["create"]
  
  resources :contacts, :only => ["index","new","create"]
  resources :comments, :only => ['index'] do
  collection do
      post :post_comment
      post :view_all
    end
  end
  
  match 'counters/batch', :via => :get

  root :to => 'ozmains#index'

end

app/controllers/ozmains_controller.rb
class OzmainsController < OzController
  
  def index
    @contact = Contact.new
    if current_flyer
      @contact.user_name = current_flyer.flyer_name
      @contact.email = current_flyer.email
    end
    breadcrumb :root
  end
  
  def uzatt
    session[:uzatt] = true
  end
  
  def about
    @contact = Contact.new
    @t = params[:t]
    contact_type = params[:contact_type]
    if contact_type.present? && Contact::CONTACT_lIST[contact_type.to_i]
      @contact.contact_type = contact_type 
    end
    if current_flyer
      @contact.user_name = current_flyer.flyer_name
      @contact.email = current_flyer.email
    end
  end
  
  # Ajax
  def recent_top_feed
    @recent_top_feed = TopFeedList.recent_top_feed(5)
  end
  
  # Ajax
  def recent_comment_feed
    @recent_comment_feed = Comment.recent_feed
  end
  
end

app/helpers/ozmain_helper.rb
module OzmainHelper
 
  def signin(text)
    #html = %Q|#{t(text)}#{link_to(facebook,flyer_omniauth_authorize_path(:facebook),:class => "")} #{link_to(google,flyer_omniauth_authorize_path(:google_oauth2),:class => "")}|
    html = %Q|<a href="\#ozj_signin_modal", role="button", class="btn" data-toggle="modal"><i class="icon-signal"></i>#{t("auth.signin")} #{facebook} #{google}</a>|
    html.html_safe
  end
  
  def show_flyer_header(flyer=nil)
    return "" if flyer.nil? && !current_flyer
    if flyer.nil?
      flyer = current_flyer
    end
    html = %Q|<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">|
    if !flyer.flyer_image.present?
      html += %Q|<i class="icon-user"></i>#{flyer.flyer_name}|
    else
      html += flyer.flyer_name
    end
    html += %Q|<span class="caret"></span></a><ul class="dropdown-menu">|
    if flyer.flyer_url.present?
      html += %Q|<li><a href="#{flyer.flyer_url}">#{t("auth.view_profile")}</a><li>|
    end
    html += %Q|<li><a href="#{destroy_flyer_session_path}"><i class="icon-leaf icon-white"></i>#{t("auth.signout")}</a></li>|
    html += "</ul>&nbsp;"
    if flyer.flyer_image.present?
      html += image_tag(flyer.flyer_image, :alt => "")
    end
    html.html_safe
  end

  def show_flyer(flyer=nil)
    html = ""
    return "" if flyer.nil? && !current_flyer
    if flyer.nil?
      flyer = current_flyer
    end
    if flyer.flyer_url.present?
      html += %Q|<a href="#{flyer.flyer_url}">#{flyer.flyer_name}</a>|
    else
      html += flyer.flyer_name
    end
    if flyer.flyer_image.present?
      html += image_tag(flyer.flyer_image, :alt => "")
    end
    html.html_safe
  end
  
  def show_flyer_name
    return current_flyer.flyer_name
  end
  
end

app/views/ozmains/_all_heading.html.erb
<% OzjapaneseStyle.heading_groups.each_with_index do |group,i| %>
<div class="row-fluid">
	<% group.each do |heading| %>
	<div class="span6" id="page_<%= heading%>">
		<h2> <%= OzjapaneseStyle.heading_name(heading)%> </h2>
		<p>
			<% if @feed[heading][0] > 0 %>
			<%= link_to(t("post.today_post"), Ozlink.heading_link(heading,"feed_view",{:f => "today"}), :onclick => '_scroll_top()', :remote => true, :method => :get) %>
			&nbsp;<span class="badge badge-info"><%= @feed[heading][0] %></span>
			<% else %>
			<%= t("post.today_post") %>&nbsp;<%= @feed[heading][0] %>
			<% end %>
		</p>
		<p>
			<% if @feed[heading][1] > 0 %>
			<%= link_to(t("post.yesterday_post"), Ozlink.heading_link(heading,"feed_view",{:f => "yesterday"}), :onclick => '_scroll_top()', :remote => true, :method => :get) %>
			&nbsp;<span class="badge badge-info"><%= @feed[heading][1] %></span>
			<% else %>
			<%= t("post.yesterday_post") %>&nbsp;<%= @feed[heading][1] %>
			<% end %>
		</p>
		<p>
			<% if @feed_cnt[heading] > 0 %>
			<%= link_to(t("post.recent_post"), Ozlink.heading_link(heading,"feed_view",{:f => "recent_week"}), :onclick => '_scroll_top()', :remote => true, :method => :get) %>
			&nbsp;<span class="badge badge-success"><%= @feed_cnt[heading]%></span>
			<% else %>
			<%= t("post.recent_post") %>&nbsp;<%= @feed_cnt[heading]%>
			<% end %>
		</p>
		<p>
			<%= t("#{heading}.desc")%>
		</p>
		<p style="margin-top: 40px">
			<div class="btn-toolbar">
				<div class="btn-group dropup">
					<%= post_write_new(heading, :signin_with_following)%>
				</div>
				<div class="btn-group">
					<%= link_to_with_icon("#{t("post.newer")} &raquo",Ozlink.heading_link(heading,"newer"),"btn btn-link","","icon-zoom-in","#{heading}_view_details") %>
				</div>
				<div class="btn-group">
					<%= link_to_with_icon("#{t("post.older")} &raquo",Ozlink.heading_link(heading,"older"),"btn btn-link","","icon-zoom-in","#{heading}_view_details") %>
				</div>
			</div>
		</p>
	</div>
	<% end %>
</div>
<% end%>

app/views/ozmains/_carousel_comment.html.erb
<div id="side_comment_thread_<%= @post.id%>">
	<%= show_comment_thread(@post, @heading)%>
</div>

app/views/ozmains/_contact_us.html.erb
<a href="<%= about_ozmains_path(:t => "contact") %>", class="btn btn-primary btn-large" id="ozj_contact_us_modal"><i class="icon-info-sign icon-white"></i><%= t(:contact_us)%> &raquo;</a>
<!--
<a href="#contact_us", role="button", class="btn btn-primary btn-large" data-toggle="modal" id="ozj_contact_us_modal"><i class="icon-info-sign icon-white"></i><%= t(:contact_us)%> &raquo;</a>
<div class="modal hide fade" id="contact_us" tabindex="-1" role="dialog" aria-labelledby="contact_us_label" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
			×
		</button>
		<h3 id="contact_us_label"><%= t("contact.label")%></h3>
	</div>
	<div class="modal-body" id="contact_us" style="font-size:12px">
		<%= render :partial => "ozmains/contact_us_form" %>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">
			<%= t(:close)%>
		</button>
	</div>
</div>
-->

app/views/ozmains/_contact_us_form.html.erb
<div class="contact_form">
	<%= form_for(@contact) do |f| %>
	<%= form_error_messages!(@contact) %>
	<%= f.label :user_name, t("contact.user_name"), :class => "" %>
	<%= f.text_field :user_name, :class => "input-xlarge" %>
	<%= f.label :email, t("contact.email"), :class => "" %>
	<div class="input-prepend">
		<span class="add-on">@</span><%= f.email_field :email, :class => "input-xlarge" %>
	</div>
	<%= f.label :phone, t("contact.phone"), :class => "" %>
	<%= f.telephone_field :phone, :class => "input-medium" %>
	<span class="help-inline"><p class="text-success"><%=t("contact.phone_is_optional")%></p></span>
	<%= f.label :contact_type, t("contact.subject"), :class => "" %>
	<%= f.select :contact_type, options_from_collection_for_select(@contact.category_list, :second, :first, @contact.contact_type) %>
	<span class="help-inline"><p class="text-success"><%=t("contact.select_contact_type")%></p></span>
	<%= f.label :body, t("contact.content"), :class => "" %>
	<%= f.text_area :body, :rows => "10", :style => "width:400px" %>
		<span class="help-inline"><p class="text-success"><%=t("contact.describe_detail")%></p></span>
	<div class="left">
		<%= f.submit t("contact.send"), :class => "btn btn-inverse", :remote => true , :method => :post, :data => { :confirm => t('confirm_submit') } %>
	</div>
	<% end %>
</div>

app/views/ozmains/_open_view.html.erb
<div class="row-fluid">
	<div class="span8" id="side_post_area">
		<%= show_posts(@posts, @heading, Common.uniqe_token)%>
	</div>
	<div class="span4" id="side_comment_area">
		<div id="side_comment_thread_<%=@posts.first.id%>">
		<%= show_comment_thread(@posts.first, @heading)%>
		</div>
	</div>
</div>

app/views/ozmains/_recent_comment_feed.html.erb
<ul class="thumbnails">
	<% @recent_comment_feed.each do |comment|%>
	<li class="" style="margin-left: 0px">
		<div class="thumbnail">
			<p>
				<%= link_to(I18n.t(comment.commented_type), Ozlink.heading_link(OzjapaneseStyle.heading_by_model(comment.commented_type),"newer"))%>
				<span class="badge badge-success"><i class="icon-camera icon-white"></i><%=comment.commented_id%></span>
			</p>
			<p>
				<%= show_flyer(comment.commented_by)%>
			</p>
			<p>
				<%= link_to(comment.body,Ozlink.heading_link(OzjapaneseStyle.heading_by_model(comment.commented_type),"link_view",{:d => comment.commented_id}))%>
			</p>
			<p>
				<%= comment.postedDate %>
			</p>
		</div>
	</li>
	<% end %>
</ul>

app/views/ozmains/_recent_top_feed.html.erb
<ul class="thumbnails">
	<% @recent_top_feed.each do |feed|%>
	<li class="" style="margin-left: 0px">
		<%= show_a_post_box(feed.feeded_to)%>
	</li>
	<% end %>
</ul>

app/views/ozmains/_site_detail.html.erb
<a href="<%= about_ozmains_path %>", class="btn btn-primary btn-large" id="ozj_site_detail_modal"><i class="icon-info-sign icon-white"></i><%= t(:view_site_detail)%> &raquo;</a>

app/views/ozmains/_view_heading.html.erb
<div class="row-fluid">
	<h3><%=OzjapaneseStyle.heading_name(@heading)%></h3>
	<div class="btn-toolbar">
		<% if @posts.present? %>
		<div class="btn-group">
			<%= link_to_with_icon("#{t("post.newer")}",Ozlink.heading_link(@heading,"newer"),"btn btn-link","","icon-plus","")%>
		</div>
		<div class="btn-group">
			<%= link_to_with_icon("#{t("post.older")}",Ozlink.heading_link(@heading,"older"),"btn btn-link","","icon-tag","")%>
		</div>
		<% end %>
		<div class="btn-group">
			<%= post_write_new(@heading, :signin_with_following)%>
		</div>
	</div>	
	<% if @posts.present? %>
	<%= show_posts(@posts, @heading, Common.uniqe_token)%>
	<% else %>
	<%= t("post.be_the_first")%>
	<% end %>
</div>
<div class="span5 offset2">
	<div id="side_comment_area">
	<% if @posts.present? %>
	<div class="" id="side_comment_thread_<%=@posts.first.id%>">
	<%= show_comment_thread(@posts.first, @heading)%>
	</div>
	<% end %>
	</div>
</div>

app/views/ozmains/about.html.erb
<div class="row">
	<ul class="nav nav-pills" id="ozjapanese_about">
    <li class="active"><a href="#oz_style"><%= t("flyer") %></a></li>
    <li><a href="#service"><%= t("terms_of_service_agreement")%></a></li>
    <li><a href="#personal"><%= t("terms_of_personal_agreement")%></a></li>
    <li><a href="#contact"><%= t("contact_us") %></a></li>
    </ul>
     
    <div class="tab-content">
    <div class="tab-pane active" id="oz_style">
    	<%= OzjapaneseStyle.about_site %>
    </div>
    <div class="tab-pane" id="service">
    	<%= simple_format(Terms.terms_of_service) %>
    	
    </div>
    <div class="tab-pane" id="personal">
    	<%= simple_format(Terms.terms_of_personal_info) %>
    	
    </div>
    <div class="tab-pane" id="contact">
    	<%= show_notice %>
    	<%= render :partial => "ozmains/contact_us_form" %>
    	
    </div>
    </div>
     
    <script>
    $('#ozjapanese_about a').click(function (e) {
    e.preventDefault();
    $(this).tab('show');
    })
    </script>
    <%= _script_document_ready(%Q|$('\#ozjapanese_about a[href="\##{@t}"]').tab('show');|)%>
</div>

app/views/ozmains/index.html.erb
<%= show_alert %>
<%= render :partial => "layouts/sns" %>	
<div class="row-fluid" id="open_view">
<% if !session[:uzatt]%>
<div class="hero-unit">
	<h1><%= raw(t(:hello_world)) %></h1>
	<p>
		<%= OzjapaneseStyle.hello_description%>
	</p>
	<%= render :partial => "ozmains/contact_us" %>
	<%= render :partial => "ozmains/site_detail" %>
	<%= link_to(t("uzatt"), uzatt_ozmains_path, :remote => true, :method => :post, :id => "", :class => "btn btn-info btn-small pull-right") %>
</div>
<% end %>
</div>

<div class="container-fluid">
<div class="row-fluid">
<%= fb_shout %>
<div class="span2" style="margin-left: 0px">
	<p class="lead"><span class="label label-inverse"><i class="icon-glass icon-white"></i><%=t("post.hot.post")%></span></p>
	<div class="row-fluid" id="recent_top_feed_area">
		<%=image_tag("ajax-loader.gif")%>
    </div>
</div>

<div class="span8">
<div class="row-fluid" id="menu">
	<ul class="pager">
		<% OzjapaneseStyle.all_headings.each do |heading| %>
		<li><%= link_to(OzjapaneseStyle.heading_name(heading),"#", :class => "shadow", :onclick => "_activate_heading_#{heading}();return false;")%></li>
		<%= _script(%Q|
			function _activate_heading_#{heading}() {
				
			| +
			
				Ajax.post(select_heading_ozs_path,%Q|v: '#{Ozlink.base(heading)}'|) + %Q|}|)%>
		<% end %>
	</ul>
	<div class="row-fluid" id="heading_group_all">
	<%=image_tag("ajax-loader.gif")%>
	</div>
		<%= _script(%Q|
		function _scroll_top() {
  			$('html,body').animate({ scrollTop: 0 }, 'slow');
  			$('\#open_view').html('#{image_tag("ajax-loader.gif")}');
		};
		|)%>

</div>
</div>

<div class="span2" style="margin-right: 0px">
	<p class="lead"><span class="label label-inverse"><i class="icon-comment icon-white"></i><%=t("post.hot.comment")%></span></p>
	<div class="row-fluid" id="recent_comment_feed_area">
		<%=image_tag("ajax-loader.gif")%>
    </div>
</div>


</div>
</div>
<%= _script_document_ready(%Q|_activate_heading_ozj_all();| +
	Ajax.post(recent_top_feed_ozmains_path,"") + 
	Ajax.post(recent_comment_feed_ozmains_path,""));
%>

app/views/ozmains/recent_comment_feed.js.erb
$('#recent_comment_feed_area').html("<%= escape_javascript(render 'ozmains/recent_comment_feed')%>");

app/views/ozmains/recent_top_feed.js.erb
$('#recent_top_feed_area').html("<%= escape_javascript(render 'ozmains/recent_top_feed')%>");

app/views/ozmains/uzatt.js.erb
$('div.hero-unit').hide('slow');