config/routes.rb
OzjapaneseComAu::Application.routes.draw do
  
  resources :ozmains, :only => ["index"] do
    collection do
      get :about
      post :uzatt
      post :recent_top_feed
      post :recent_comment_feed
    end
  end
  
  resources :sessions, :only => [] do
    collection do
      post :signin
    end
  end
  
  devise_for :flyers, :controllers => { :omniauth_callbacks => "flyers/omniauth_callbacks" }
  
  resources :ozs, :only => ['index'] do
    collection do
      get :older
      get :newer
      get :write
      get :cancel
      post :viewed
      get :link_view
      post :carousel_viewed
      get :feed_view
      post :select_heading
      post :upload_image
    end
  end
  
  
  resources :terms, :only => ["index","create"]
  resources :images, :only => ["create"]
  resources :oz_employments, :only => ["create"]
  resources :oz_employers, :only => ["create"]
  resources :oz_sell_goods, :only => ["create"]
  resources :oz_buy_goods, :only => ["create"]
  resources :oz_estate_share_rents, :only => ["create"]
  resources :oz_info_events, :only => ["create"]
  resources :oz_people_pros, :only => ["create"]
  resources :oz_info_living_smarts, :only => ["create"]
  resources :oz_info_living_qnas, :only => ["create"]
  
  resources :contacts, :only => ["index","new","create"]
  resources :comments, :only => ['index'] do
  collection do
      post :post_comment
      post :view_all
    end
  end
  
  match 'counters/batch', :via => :get

  root :to => 'ozmains#index'

end

app/views/layouts/_facebook.html.erb
<script>
	window.fbAsyncInit = function() {
		FB.init({
			appId : '254068608049050', // App ID
			channelUrl : '//www.ozjapanese.com.au/channel.html', // Channel File
			status : true, // check login status
			cookie : true, // enable cookies to allow the server to access the session
			xfbml : true // parse XFBML
		});
		//FB.ui({
		//  method: 'feed'
		//});
	};
	// Load the SDK Asynchronously
	( function(d) {
			var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
			if (d.getElementById(id)) {
				return;
			}
			js = d.createElement('script');
			js.id = id;
			js.async = true;
			js.src = "//connect.facebook.net/en_US/all.js";
			ref.parentNode.insertBefore(js, ref);
		}(document)); 
</script>

app/views/layouts/_footer.html.erb
<hr>
<footer>
	<p>
		&copy; IT.KoolBZ <%= Common.copy_right_year %> ABN 42253612817 Supported &amp; Developed by <%= t("ozflyer") %>
		<%= link_to(t("flyer"), about_ozmains_path) %>
	</p>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
			<a class="brand" href="<%=root_path%>"><i class="icon-fire icon-white"></i><%= t(:project_name)%><%=t(:brisbane)%><small><%=t(:goldcoast)%></small>&nbsp;<%=t(:header_message)%></a>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li></li>
				</ul>
				<div class="span5 pull-right">
					<div class="navbar-text pull-right">
						<% if controller.controller_name.eql?("terms")%>
							<%=t("signin_agreement_required")%>
						<% else %>
							<strong style="font-size:20px"><%=OzjapaneseStyle.greeting%></strong>
							<% if !current_flyer %>
								<%= signin(:signin_with) %>
							<% else %>
								<%= show_flyer_header %>
							<% end %>
						<% end %>
					</div>
				</div>
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>

app/views/layouts/_signin.html.erb
<div class="modal hide fade" id="ozj_signin_modal" tabindex="-1" role="dialog" aria-labelledby="ozj_signin_modal_label" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
			×
		</button>
		<h3 id="ozj_signin_modal_label"><%= t("auth.signin") %> <%=facebook%> <%=google%></h3>
	</div>
	<div class="modal-body">
		<ul class="thumbnails">
			<li class="span5">
				<div class="thumbnail">	
					<h6><%= facebook %> <%=t("auth.with_facebook")%></h6>
					<p><%=t("auth.signin_with_how", :provider => "Google")%></p>
					<p>
					<label class="checkbox">
					<input type="checkbox" value="" id="facebook_remember_me">
					<%=t("auth.remember_me")%>
					</label>
					</p>
					<button type="button" class="btn btn-primary" data-loading-text="<%=t("signin_inprogress")%>" id="facebook_signin"><%=t("auth.process_signin")%></button>
					<div class="facebook_signin_progress"></div>
					<%= _script_document_ready(%Q|$('\#facebook_signin').button();
						$('\#facebook_signin').click(function() {
						$('.facebook_signin_progress').html('#{image_tag("ajax-loader.gif")}');| +
						Ajax.post(signin_sessions_path,%Q|remember_me:$('\#facebook_remember_me').attr("checked"),provider:'#{Flyer::PROVIDERS[:facebook]}'|) +
						%Q|})|)%>
				</div>
			</li>
			<li class="span5">
				<div class="thumbnail">			
					<h6><%= google %> <%=t("auth.with_google")%></h6>
					<p><%=t("auth.signin_with_how", :provider => "Google")%></p>
					<p>
					<label class="checkbox">
					<input type="checkbox" value="" id="google_remember_me">
					<%=t("auth.remember_me")%>
					</label>
					</p>
					<button type="button" class="btn btn-primary" data-loading-text="<%=t("signin_inprogress")%>" id="google_signin"><%=t("auth.process_signin")%></button>			
					<div class="google_signin_progress"></div>
					<%= _script_document_ready(%Q|
						$('\#google_signin').button();
						$('\#google_signin').click(function() {
						$('.google_signin_progress').html('#{image_tag("ajax-loader.gif")}');| +
						Ajax.post(signin_sessions_path,%Q|remember_me:$('\#google_remember_me').attr("checked"),provider:'#{Flyer::PROVIDERS[:google]}'|) +
						%Q|})|)%>
				</div>
			</li>
			<% if debug? %>
			<li class="span5">
				<div class="thumbnail">			
					<h6>OzJapanese Signin</h6>
					<button type="button" class="btn btn-primary" data-loading-text="<%=t("signin_inprogress")%>" id="ozjapanese_signin"><%=t("auth.process_signin")%></button>
					<div class="ozjapanese_signin_progress"></div>
					<%= _script_document_ready(%Q|
						$('\#ozjapanese_signin').button();
						$('\#ozjapanese_signin').click(function() {
						$('.ozjapanese_signin_progress').html('#{image_tag("ajax-loader.gif")}');| +
						Ajax.post(signin_sessions_path,%Q|provider:'#{Flyer::PROVIDERS[:ozjapanese]}'|) +
						%Q|})|)%>
				</div>
			</li>

			<% end %>
		</ul>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">
			<%= t(:close)%>
		</button>
	</div>
</div>

app/views/layouts/_sns.html.erb
<div id="sns">
<div id="fb-root"></div>  
    <script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
	<script type="IN/Share" data-counter="right"></script>
	<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
	<g:plusone></g:plusone>
	<script type="text/javascript">
		(function() {
			var po = document.createElement('script');
			po.type = 'text/javascript';
			po.async = true;
			po.src = 'https://apis.google.com/js/plusone.js';
			var s = document.getElementsByTagName('script')[0];
			s.parentNode.insertBefore(po, s);
		})();
	</script>
	<a href="https://twitter.com/share" class="twitter-share-button" data-lang="ja">ツイート</a>
	<script>
		! function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (!d.getElementById(id)) {
				js = d.createElement(s);
				js.id = id;
				js.src = "//platform.twitter.com/widgets.js";
				fjs.parentNode.insertBefore(js, fjs);
			}
		}(document, "script", "twitter-wjs");
	</script>
	<div class="fb-like" data-send="true" data-width="450" data-show-faces="true"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=t(:title)%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => "layouts/header" %>
<%= render :partial => "layouts/facebook" %>
<%= render :partial => "layouts/signin" %>
<div class="container" style="margin-top:100px">
<%= breadcrumb :pretext => "",
               :posttext => "",
               :separator => " &rsaquo; ",
               :autoroot => true,
               :show_root_alone => true,
               :link_current => true,
               :semantic => false
               %>
<%= yield %>
<%= render :partial => "layouts/footer" %>
</div>
</body>
</html>